name: continuous integration

on:
  push:
    branches:
      - master
      - main
      - feature/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        exporter: [ "blackbox-exporter" ]

    steps:
      - uses: actions/checkout@v3

      - name: build Docker file
        uses: docker/build-push-action@v4
        with:
          file: ${{ matrix.exporter }}/Dockerfile
          push: false
