name: release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        exporter: [ "blackbox-exporter" ]

    steps:
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: build Docker file
        uses: docker/build-push-action@v4
        with:
          file: ${{ matrix.exporter }}/Dockerfile
          push: true
          tags: |
            ghcr.io/ping7io/${{ matrix.exporter }}:latest
